/* @flow */

export const ActionStates = {
	REQUEST: 'REQUEST',
	FAIL: 'FAIL',
	COMPLETE: 'COMPLETE',
};

export const INTL_LOCALE_SET = 'INTL_LOCALE_SET';
export const INTL_SET = 'INTL_SET';

export const USER_SIGN_IN_COMPLETE = 'USER_SIGN_IN_COMPLETE';

export const SETTINGS_FETCH_COMPLETE = 'SETTINGS_FETCH_COMPLETE';
export const SETTINGS_UPDATE_COMPLETE = 'SETTINGS_UPDATE_COMPLETE';
